/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JOBAYER HOSSAIN
 */

import java.awt.Color;

import javax.swing.UIManager;

import javax.swing.UIManager.LookAndFeelInfo;

import javax.swing.UnsupportedLookAndFeelException;

import javax.swing.JFrame;

import javax.swing.JOptionPane;

import java.awt.event.ActionEvent;

import java.awt.event.ActionListener;

import javax.swing.JFrame;

import javax.swing.Timer;

import javax.swing.*;

import java.awt.*;

import java.awt.event.*;

import java.util.*;

public class TICTACTOE extends javax.swing.JFrame 

{

    private String startgame= "X";
    
    private int xcounter = 0;
    
    private int ocounter = 0;
    
    private boolean win;
    
    private int count = 0;
    
    /**
     * Creates new form TICTACTOE
     */
    
    public TICTACTOE() 
    
    {
        initComponents();
        
        gamescore();
    }

    private void gamescore()
   
    {
       
        jlblplayerx.setText(String.valueOf(xcounter));
        
        
        jlblplayero.setText(String.valueOf(ocounter));
        
    }
    
    private void chooseaplayer()
    
    {
        if(startgame.equalsIgnoreCase("X"))
            
        {
            
            startgame="O";
       
        }
        else
        
        {
            
                startgame ="X";
        }
        
    }
    
    private boolean winninggame()
            
    {
        String b1 = jButton1.getText();
        
        
        String b2 = jButton2.getText();
        
        String b3 = jButton3.getText();
        
        String b4 = jButton4.getText();
        
        String b5 = jButton5.getText();
        
        String b6 = jButton6.getText();
        
        String b7 = jButton7.getText();
        
        String b8 = jButton8.getText();
        
        String b9 = jButton9.getText();
        
       
        
        if (b1 == b2 && b2 == b3 && b1 != "") 
        
        {          
            win = true;
        
        }
        
        else if (b4 == b5 && b5 == b6 && b4 != "") 
        
        {
           
            win = true;
        } 
        
        else if (b7 == b8 && b8 == b9 && b7 != "") 
        
        {
           
            win = true;
        } 

        //virticle wins
        
        else if (b1 == b4 && b4 == b7 && b1 != "") 
        
        {
           
            win = true;
        } 
        
        else if (b2 == b5 && b5 == b8 && b2 != "") 
        
        {
          
            win = true;
       
        } 
        
        else if (b3 == b6 && b6 == b9 && b3 != "") 
        
        {
            
            win = true;
        
        } 

        //diagonal wins
        
        else if (b1 == b5 && b5 == b9 && b1 != "")
        
        {
            
            
            win = true;
      
        
        } 
        
        else if (b3 == b5 && b5 == b7 && b3 != "")
        
        {
            
            
            win = true;
        }
        
        else
        
        {
        
        
            win = false;
        }
        return win;
           
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlblplayero = new javax.swing.JLabel();
        jlblplayerx = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 96)); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 130, 90));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 96)); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 130, 90));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 96)); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 130, 90));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 96)); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 130, 90));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 96)); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 130, 90));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 96)); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 130, 90));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 96)); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 130, 90));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 96)); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 130, 90));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 96)); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 130, 90));

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jButton10.setText("EXIT");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 320, 110, 70));

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jButton11.setText("RESET");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 130, 70));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Player O :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Player X :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, -1, -1));

        jlblplayero.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jlblplayero.setText("jLabel3");
        getContentPane().add(jlblplayero, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, -1, -1));

        jlblplayerx.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jlblplayerx.setText("jLabel3");
        getContentPane().add(jlblplayerx, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 730, -1));

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jButton12.setText("BACK");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 120, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        // TODO add your handling code here:
        
       jButton2.setText(startgame);
       
       
        if(startgame.equalsIgnoreCase("X"))
        {
            jButton2.setForeground(Color.green);
         
        }
        
        else
       
        {
           
            jButton2.setForeground(Color.BLUE);
       
        }
     
       
    
        chooseaplayer();
        
         ++count;
      
        if (winninggame() == true) 
        
        {
            if(startgame=="X")
            
            {
            
                
                JOptionPane.showMessageDialog(null, "O" + " WINS!");
                
                
                ocounter++;
            
            }
                else
            
            {
             
                JOptionPane.showMessageDialog(null, "X" + " WINS!");
                
                xcounter++;
            }
                
        }
        else if (count == 9 && win == false)
        
        {
           
            JOptionPane.showMessageDialog(null, "Tie Game!");
        
        }
        
        gamescore();

        
    }//GEN-LAST:event_jButton2ActionPerformed
      
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        

        // TODO add your handling code here:
        
        
        jButton6.setText(startgame);
        
        
        if(startgame.equalsIgnoreCase("X"))
        
        {
            
            jButton6.setForeground(Color.green);
        
        }
        
        else
        
        {
         
            jButton6.setForeground(Color.BLUE);
        
        }
        
        
        chooseaplayer();
        
        ++count;
        
        if (winninggame() == true) 
        
        {
        
            if(startgame=="X"){
                
            JOptionPane.showMessageDialog(null, "O" + " WINS!");
            
            ocounter++;
            
            }
            
            else
                
            {
                JOptionPane.showMessageDialog(null, "X" + " WINS!");
                
                xcounter++;
            
            }
                
        } 
        else if (count == 9 && win == false) 
        
        {
        
            JOptionPane.showMessageDialog(null, "Tie Game!");
        
        }
        
        gamescore();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       
        // TODO add your handling code here:
        
        jButton8.setText(startgame);
        
        if(startgame.equalsIgnoreCase("X"))
        
        {
        
            jButton8.setForeground(Color.green);
        
        }
        
        else
        
        {
        
            jButton8.setForeground(Color.BLUE);
        
        }
        
                chooseaplayer();
        
        ++count;
        
        if (winninggame() == true) 
        
        {
        
            if(startgame=="X"){
                
            JOptionPane.showMessageDialog(null, "O" + " WINS!");
            
            ocounter++;
            
            }
            
            else
                
            {
                JOptionPane.showMessageDialog(null, "X" + " WINS!");
                
                xcounter++;
                
                
                
            }
                
        } 
        else if (count == 9 && win == false) 
        
        {
        
            JOptionPane.showMessageDialog(null, "Tie Game!");
        
        }
        
        gamescore();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        

        // TODO add your handling code here:
        
        jButton1.setText(startgame);
        
        if(startgame.equalsIgnoreCase("X"))
        
        {
        
            jButton1.setForeground(Color.green);
        
        }
        else
        
        {
        
            jButton1.setForeground(Color.BLUE);
        
        }
        
         chooseaplayer();
        
        ++count;
        
        if (winninggame() == true) 
        
        {
        
            if(startgame=="X"){
                
            JOptionPane.showMessageDialog(null, "O" + " WINS!");
            
            ocounter++;
            
            }
            
            else
                
            {
                JOptionPane.showMessageDialog(null, "X" + " WINS!");
                
                xcounter++;
                
            }
                
        } 
        else if (count == 9 && win == false) 
        
        {
        
            JOptionPane.showMessageDialog(null, "Tie Game!");
        
        }
        
        gamescore();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        

        // TODO add your handling code here:
        
        jButton3.setText(startgame);
        
        if(startgame.equalsIgnoreCase("X"))
        
        {
        
            jButton3.setForeground(Color.green);
        
        }
        
        else
        
        {
        
            jButton3.setForeground(Color.BLUE);
        
        }
        
         chooseaplayer();
        
        ++count;
        
        if (winninggame() == true) 
        
        {
        
            if(startgame=="X"){
                
            JOptionPane.showMessageDialog(null, "O" + " WINS!");
            
            ocounter++;
            
            }
            
            else
                
            {
                JOptionPane.showMessageDialog(null, "X" + " WINS!");
                
                xcounter++;
                
            }
                
        } 
        else if (count == 9 && win == false) 
        
        {
        
            JOptionPane.showMessageDialog(null, "Tie Game!");
        
        }
        
        gamescore();
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        // TODO add your handling code here:
        
        jButton4.setText(startgame);
        
        if(startgame.equalsIgnoreCase("X"))
        
        {
        
            jButton4.setForeground(Color.green);
        
        }
        
        else
        
        {
        
            jButton4.setForeground(Color.BLUE);
       
        }
        
        chooseaplayer();
        
        ++count;
        
        if (winninggame() == true) 
        
        {
        
            if(startgame=="X"){
                
            JOptionPane.showMessageDialog(null, "O" + " WINS!");
            
            ocounter++;
            
            }
            
            else
                
            {
                JOptionPane.showMessageDialog(null, "X" + " WINS!");
                
                xcounter++;
                
            }
                
        } 
        else if (count == 9 && win == false) 
        
        {
        
            JOptionPane.showMessageDialog(null, "Tie Game!");
        
        }
        gamescore();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       
        // TODO add your handling code here:
        
        jButton5.setText(startgame);
        
        if(startgame.equalsIgnoreCase("X"))
        
        {
        
            jButton5.setForeground(Color.green);
        
        }
        
        else
        
        {
        
            jButton5.setForeground(Color.BLUE);
        
        }
        
        chooseaplayer();
        
        ++count;
        
        if (winninggame() == true) 
        
        {
        
            if(startgame=="X"){
                
            JOptionPane.showMessageDialog(null, "O" + " WINS!");
            
            ocounter++;
            
            }
            
            else
                
            {
                JOptionPane.showMessageDialog(null, "X" + " WINS!");
                
                xcounter++;
                
            }
                
        } 
        else if (count == 9 && win == false) 
        
        {
        
            JOptionPane.showMessageDialog(null, "Tie Game!");
        
        }
        
        gamescore();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       
        // TODO add your handling code here:
        
        jButton7.setText(startgame);
        
        if(startgame.equalsIgnoreCase("X"))
        
        {
        
            jButton7.setForeground(Color.green);
        
        }
        
        else
        
        {
        
            jButton7.setForeground(Color.BLUE);
        
        }
        
         chooseaplayer();
        
        ++count;
        
        if (winninggame() == true) 
        
        {
        
            if(startgame=="X")
            
            {
                
            JOptionPane.showMessageDialog(null, "O" + " WINS!");
            
            ocounter++;
            
            }
            
            else
                
            {
                JOptionPane.showMessageDialog(null, "X" + " WINS!");
                
                xcounter++;
                
            }
                
        } 
        else if (count == 9 && win == false) 
        
        {
        
            JOptionPane.showMessageDialog(null, "Tie Game!");
        
        }
        
        gamescore();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        
        // TODO add your handling code here:
        
        jButton9.setText(startgame);
        
        if(startgame.equalsIgnoreCase("X"))
        
        {
        
            jButton9.setForeground(Color.green);
        
        }
        
        else
        
        {
        
            jButton9.setForeground(Color.BLUE);
        
        }
        
        chooseaplayer();
        
        ++count;
        
        if (winninggame() == true) 
        
        {
        
            if(startgame=="X"){
                
            JOptionPane.showMessageDialog(null, "O" + " WINS!");
            
            ocounter++;
            
            }
            
            else
                
            {
                JOptionPane.showMessageDialog(null, "X" + " WINS!");
                
                xcounter++;
                
            }
                
        } 
        else if (count == 9 && win == false) 
        
        {
        
            JOptionPane.showMessageDialog(null, "Tie Game!");
        
        }
        
        gamescore();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        

    // TODO add your handling code here:
        
        
        jButton1.setText("");
        
        jButton2.setText("");
        
        jButton3.setText("");
        
        jButton4.setText("");

        
        jButton5.setText("");
        
        jButton6.setText("");
        
        jButton7.setText("");
        
        jButton8.setText("");
        
        jButton9.setText("");

        count = 0;
        
       
        jButton1.setBackground(Color.LIGHT_GRAY);
        
        jButton2.setBackground(Color.LIGHT_GRAY);
        
        jButton3.setBackground(Color.LIGHT_GRAY);
        
        jButton4.setBackground(Color.LIGHT_GRAY);
        
        jButton5.setBackground(Color.LIGHT_GRAY);
        
        jButton6.setBackground(Color.LIGHT_GRAY);
        
        jButton7.setBackground(Color.LIGHT_GRAY);
        
        jButton8.setBackground(Color.LIGHT_GRAY);
        
        jButton9.setBackground(Color.LIGHT_GRAY);
        
        
    }//GEN-LAST:event_jButton11ActionPerformed

    
    private JFrame frame;
    
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        
        // TODO add your handling code here:
        
        frame = new JFrame ("EXIT");
        
        
        if(JOptionPane.showConfirmDialog(frame, "Confrom if want to exit ? ","Tic tac Toe",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        
        {
        
            System.exit(0);
        
        }
       
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        
        // TODO add your handling code here:
        
        dispose();
      
    
        new choosemode().setVisible(true);
    
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TICTACTOE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TICTACTOE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TICTACTOE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TICTACTOE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
          UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                
                
                new TICTACTOE().setVisible(true);
            }
        }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlblplayero;
    private javax.swing.JLabel jlblplayerx;
    // End of variables declaration//GEN-END:variables
}
